## NUMPY ARRAYS

In [3]:
my_list = [1,2,3,4,5]

In [5]:
import numpy as np

In [9]:
arr = np.array(my_list)

In [11]:
arr

array([1, 2, 3, 4, 5])

In [13]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [17]:
np.array(my_mat)    # notice 2 [[...]] 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
np.linspace(0,100,23)

array([  0.        ,   4.54545455,   9.09090909,  13.63636364,
        18.18181818,  22.72727273,  27.27272727,  31.81818182,
        36.36363636,  40.90909091,  45.45454545,  50.        ,
        54.54545455,  59.09090909,  63.63636364,  68.18181818,
        72.72727273,  77.27272727,  81.81818182,  86.36363636,
        90.90909091,  95.45454545, 100.        ])

In [47]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
np.random.rand(5)

array([0.55436566, 0.28074085, 0.63864733, 0.8122525 , 0.18048486])

In [53]:
np.random.rand(4,5)

array([[0.48015905, 0.93055693, 0.58341263, 0.01866187, 0.16509959],
       [0.95609635, 0.14803781, 0.78474379, 0.50881119, 0.73004028],
       [0.44911274, 0.27449156, 0.18721361, 0.02867733, 0.64633111],
       [0.00201111, 0.4479668 , 0.40031473, 0.82290527, 0.64992692]])

In [55]:
np.random.randn(4)

array([ 1.0447332 ,  0.53439491,  0.20960681, -0.00172826])

In [57]:
np.random.randn(3,2)

array([[ 1.06919624,  1.29464759],
       [-1.31306088,  0.59133817],
       [-1.20096835,  0.02728863]])

In [59]:
np.random.randint(2,10,30)

array([6, 4, 7, 9, 3, 4, 7, 8, 7, 3, 4, 2, 5, 5, 4, 2, 4, 9, 9, 7, 7, 5,
       9, 5, 2, 5, 9, 8, 3, 9])

In [61]:
new_arr = np.arange(25)

In [63]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [67]:
new_arr.reshape(5,5)   # you will get error if you don't provide correct order

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
rand_arr = np.random.randint(0,50,20)

In [71]:
rand_arr

array([26, 45, 28, 41, 45,  4, 39,  1,  3,  4,  0, 34,  4, 11,  6,  0, 41,
       45, 17,  5])

In [75]:
rand_arr.max()

45

In [77]:
rand_arr.min()

0

In [79]:
rand_arr.argmin()

10

In [81]:
rand_arr.argmax()

1

In [83]:
rand_arr.shape

(20,)

In [85]:
r = rand_arr.reshape(4,5)

In [87]:
r

array([[26, 45, 28, 41, 45],
       [ 4, 39,  1,  3,  4],
       [ 0, 34,  4, 11,  6],
       [ 0, 41, 45, 17,  5]])

In [89]:
r.argmax()

1

## NUMPY ARRAY INDEXING !

In [92]:
arr = np.arange(0,11)

In [94]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
arr[5]

5

In [98]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [100]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [102]:
arr[:3] = 100

In [104]:
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [106]:
arr1 = np.arange(1,16)

In [108]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [114]:
slice_of_arr1 = arr1[:6]

In [116]:
slice_of_arr1

array([1, 2, 3, 4, 5, 6])

In [118]:
slice_of_arr1 [:] = 50

In [120]:
slice_of_arr1

array([50, 50, 50, 50, 50, 50])

In [124]:
arr1     # Notice Original Array also got altered !

array([50, 50, 50, 50, 50, 50,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [126]:
arr1_cpy = arr1.copy()

In [128]:
arr1_cpy

array([50, 50, 50, 50, 50, 50,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [130]:
arr1_cpy[:11] = 15

In [132]:
arr1_cpy

array([15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 12, 13, 14, 15])

In [138]:
arr1        # still unaltered !

array([50, 50, 50, 50, 50, 50,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [141]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [143]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [149]:
arr_2d[1][1]

5

In [151]:
arr_2d[1,1]

5

In [157]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [159]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [163]:
arr[:3] = [0,1,2]

In [165]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [169]:
arr >= 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [171]:
bool_arr = arr > 5

In [173]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [175]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [177]:
arr[arr<4]

array([0, 1, 2, 3])

In [179]:
## PRACTICE 

In [181]:
prac_arr = np.arange(1,51)

In [185]:
prac_arr.reshape(5,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [197]:
prac_arr   # its actually still an 1-d array !

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [199]:
reshaped_arr = prac_arr.copy().reshape(5,10)

In [201]:
reshaped_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [203]:
prac_arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [205]:
# ALTERNATIVELY 

In [207]:
prac_array = np.arange(0,50).reshape(5,10)

In [209]:
prac_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [217]:
### NOW WE WILL TRY TO GRAB ELEMENTS (from reshaped array) ------>  [[14, 15, 16, 17],[24, 25, 26, 27]]

In [219]:
reshaped_arr[1:3,3:7]

array([[14, 15, 16, 17],
       [24, 25, 26, 27]])

## NUMPY ARRAY OPERAION

In [7]:
import numpy as np

In [9]:
arr = np.arange(0,11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [15]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [19]:
arr/arr

C:\Users\Rohit Maity\AppData\Local\Temp\ipykernel_26632\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [21]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [23]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [25]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [29]:
np.max(arr)

10

In [31]:
arr.max()

10